version: "3.7"

services:

  frontend:
    build: ./frontend
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: ['npm', 'run', 'develop']
    # command: ["sh", "-c", "sleep 2073600"]

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/src:/usr/src/app/src
    command: ['npm', 'run', 'watch']

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ['nginx', '-g', 'daemon off;']


#  db:
#    image: postgres:9.4
#    volumes:
#      - cs-gorner-data:/var/lib/postgresql/data



volumes:
  cs-gorner-data: